### ISSUE TITLE
Wrap asset paths in a getter function

### ISSUE THREAD

**Issue by shenanigansd** [letsbuilda/tower#11]
Currently, we're using `pathlib` to find the paths to asset files, but it is a bit messy:
https://github.com/letsbuilda/tower/blob/dfa9148a9aa1e5199260d03b0e0ddb33f063fd83/src/tower/__main__.py#L35

We should wrap this in a function that takes a path relative to the assets directory, and returns the full relative path. An example implementation could look like:
```py
def get_asset_path(file_name: str) -> str:
    path = (Path(__file__).parent.parent.parent / "assets").joinpath(file_name)
    return str(path)

full_path = get_asset_path("levels/level_1.tmx")
```

We should also move the assets directory inside of the package directory, to reduce the number of `.parents` required. That will also put it in the right place if we are able to implement `importlib.resources` in the future.

**Comment by FieryIceStickie** [comment]
Isn't this resolved now since we now have `ASSETS_DIR` in ``constants.py``?
