### ISSUE TITLE
Move constants to dedicated file

### ISSUE THREAD

**Issue by shenanigansd** [letsbuilda/tower#13]
Currently, the constants are just at the top of the `__main__` file:
https://github.com/letsbuilda/tower/blob/dfa9148a9aa1e5199260d03b0e0ddb33f063fd83/src/tower/__main__.py#L9-L12

They should be moved to a dedicated file, i.e. a "`constants.py`", where they can be maintained separately.

**Comment by Anonymous4045** [comment]
I think all the path handling should be done here too rather than in functions. I.e. each dir we need can be a constant.
